### PR TITLE
Feat: Jetbrains documents

### PR DESCRIPTION
**Pull request by chottuthejimmy**
In accordance to #110

### CODE REVIEW

**Comment by chottuthejimmy** [comment]
The [settings](https://docs.pieces.app/~125/extensions-plugins/jetbrains#for-any-other-issues-with-the-pieces-for-developers-jetbrains-plugin) part I just included under the troubleshooting part. The images can be replaced/removed if it's too much @jordan-pieces

**Review by georgia-at-pieces — APPROVED** [review]

**Review by jordan-pieces — APPROVED** [review]
Thanks again @chottuthejimmy looks great! We will get some more info about each of the individual settings soon but this is a great update! :)

**Comment by jordan-pieces** [comment]
also love these sections 
Screenshot 2023-08-25 at 11 07 49 AM

@chottuthejimmy would love to get more of them added around the entire documentation site on helpful details and information

**Comment by chottuthejimmy** [comment]
haha

> also love these sections Screenshot 2023-08-25 at 11 07 49 AM
> 
> @chottuthejimmy would love to get more of them added around the entire documentation site on helpful details and information

haha again I have a pretty good memory, I had read the whole documentation of gh docs and just used it . But ya really really grateful to be a part of such an organization.

**Pull request merged**
