### PR TITLE
Updated Title Section

### PR DESCRIPTION
**Pull request by Sophyia7**
Changed the Title section from **Installation and Get Started** to **Installation** #144

### CODE REVIEW

**Comment by Sophyia7** [comment]
@jordan-pieces I don't think I can select a reviewer so I tagged you instead.

**Comment by Sophyia7** [comment]
Aright. Working on it now.

**Comment by Sophyia7** [comment]
@jordan-pieces I don't have write access to this repo so I can't push to it.

**Comment by jordan-pieces** [comment]
alright nevermind for now, we will just have to hold off on doing this. I am actually preparing some migrations for these repos to get them moved to hosting services so i will see what it looks like following that migration. If you can just hold off for now on making any updates to this repo that would be fantastic until it has settled and then we can go through the best way for you to contribute here @Sophyia7

**Comment by Sophyia7** [comment]
Alright, that's fine.

**Pull request closed without merging**
