### PR TITLE
feat: adding LightHouse Github action 

### LINKED ISSUE #280: Add Lighthouse GitHub Workflow
Add a workflow that runs lighthouse checks on any page that has been edited.

You'll have to pattern-match any of the pages against the changes files.

Should use this action: https://github.com/marketplace/actions/lighthouse-ci-action

### PR DESCRIPTION
**Pull request by CBID2**
## Description
This PR adds [workflow](https://github.com/marketplace/actions/lighthouse-ci-action) that runs lighthouse checks on any page that has been edited.

## Issue
Closes #280 

> [!NOTE]
> This is still a work-in progress @mason-at-pieces. I'm going to test this by creating a test repo. Be on the lookout for this.

### CODE REVIEW

**Comment by mason-at-pieces** [comment]
@CBID2 This is great, thank you! Were you able to get the action to run?

**Comment by CBID2** [comment]
> @CBID2 This is great, thank you! Were you able to get the action to run?

Thanks @mason-at-pieces! :) I have to test it first

**Comment by CBID2** [comment]
> @CBID2 This is great, thank you! Were you able to get the action to run?

Hey @mason-at-pieces! :) Here is a repo](https://github.com/CBID2/test-repo-for-pieces-docs/tree/main) that I created to test the GitHub action. Can you send a PR to it so I can see if it works.

**Comment by mason-at-pieces** [comment]
@CBID2 could you remove `pieces.app` from the list of URLs to check? Eventually, that list will be automatically generated based on what pages have changes to them.

Also, after we get this first test working with `docs.pieces.app`, it would be great if we could use the preview deployment link that vercel gives us instead of docs.pieces.app. You can read about how to do that here: https://github.com/orgs/vercel/discussions/439

**Comment by CBID2** [comment]
> @CBID2 could you remove `pieces.app` from the list of URLs to check? Eventually, that list will be automatically generated based on what pages have changes to them.
> 
> 
> 
> Also, after we get this first test working with `docs.pieces.app`, it would be great if we could use the preview deployment link that vercel gives us instead of docs.pieces.app. You can read about how to do that here: https://github.com/orgs/vercel/discussions/439

Hi @mason-at-pieces. I removed the `pieces.app`URL. As far as adding the deployment link, that would mean adding another GitHub Action to it, which might be a bit difficult. So, I'm going to try a different approach.

**Comment by mason-at-pieces** [comment]
Hey @CBID2, I noticed that you are using the vercel preview link in the workflow which isn't on your forked repo. We may just have to merge this in to test it out haha

**Comment by CBID2** [comment]
> Hey @CBID2, I noticed that you are using the vercel preview link in the workflow which isn't on your forked repo. We may just have to merge this in to test it out haha

Ok @mason-at-pieces. Merge time

**Review by mason-at-pieces — APPROVED** [review]
lgtm

**Pull request merged**
