### PR TITLE
Added Feat. Request for GH discussion

### PR DESCRIPTION
**Pull request by Sophyia7**
Added Feature Request for GitHub discussion

### CODE REVIEW

**Review by mason-at-pieces — CHANGES_REQUESTED** [review]
The `config.yaml` file should be in the `.github/ISSUE_TEMPLATE`

**Comment by Sophyia7** [comment]
@mason-at-pieces fixed.

**Review by mason-at-pieces — APPROVED** [review]
looks great

**Comment by mason-at-pieces** [comment]
@Sophyia7 The following changes need to be made in a new pr:

- [ ] You need to allow blank issues to be created
- [ ] Delete the `.DS_Store` file that was added

**Comment by Sophyia7** [comment]
Noted! Also, can I restore my branch? @mason-at-pieces

**Comment by mason-at-pieces** [comment]
> Noted! Also, can I restore my branch? @mason-at-pieces

It should be restored now

**Pull request merged**
