### PR TITLE
Added Blank Issue MD

### PR DESCRIPTION
**Pull request by Sophyia7**
Added Blank Issue Markdown and deleted DS_Store

### CODE REVIEW

**Comment by mason-at-pieces** [comment]
So currently, if you try to make an issue on the docs repo, it doesn't give you that option. In the config.yaml file, you need to set the blank issues option to true.

And then for this new file you've added, it should be named something like "Create an Issue" to give the user an option to create an issue.

**Comment by Sophyia7** [comment]
I missed this, working on it.

**Comment by Sophyia7** [comment]
@mason-at-pieces take a look at this again and lmk if I missed anything else.

**Review by mason-at-pieces — APPROVED** [review]
Looks great

**Pull request merged**
